### ISSUE TITLE
Will this method work with Volta

### ISSUE THREAD

**Issue by AlexVPerl** [IsmaelHG/UndervoltPatchMacBook#2]
First, thank you for creating this tool and guide. 

I was looking for a way to undervolt my mid-2104 MacBook Pro with Volta in BigSur and came across VoltageShift and your mod.

Would you happen to know if this method will work with Volta as well?

**Comment by IsmaelHG** [comment]
Volta is a broken app since Catalina. This method will allow you tu use Volta but only on Mojave and earlier versions.

**Comment by AlexVPerl** [comment]
Thanks for the reply. I liked Volta because it has a UI, but I guess the only current option is to use VoltageShift with your mod. I've never done a rom flash using external programmer before, but very inclined to try this out. 

Should I disconnect the battery from the motherboard before flashing? 

Also if you have any other tips for someone trying this out for first time, it would be very welcomed :)

**Comment by teqtic** [comment]
Volta still works for me on Big Sur after patching my EFI chip as detailed by this guide. However, I now prefer VoltageShift as it allows you to undervolt the GPU and CPU cache as well. However, I'm still not sure which GPU it undervolts, the intel integrated GPU or the dedicated GPU?
