### ISSUE TITLE
Bricked my rMBP 2013?

### ISSUE THREAD

**Issue by imloualvaro** [IsmaelHG/UndervoltPatchMacBook#3]
I did all the process on osx 11.3 with success, but after 11.5 I did same and my rMBP doesn't startup properly. Could you guys give me some help to figure out what's going wrong?

The process I follow was:
1. I did boot with Linux ubuntu 18, on terminal I did use `sudo flashrom --programmer internal -r backup.rom -c MX25L6406E/MX25L6408E` to dump eprom original rom.

2. Copy the the file to a Win10 PC and with a ch341a mini and SOP8 I connected to the eprom chip.

3. After patch the original rom with UEFI I tried to write the new patched rom using ch341A programmer v1.29 and all I did get was "CHIP MAIN MEMORY WITH THE CONTENTS ARE IN DISAGREEMENT" error. I tried different programmer versions as v1.18, v1.30 and get same message.

4. After that my MacBook didn't startup.

5. I tried to revert all trying to flash my backup but all I can get is same error. Only fan start to spin when I try to start my rMBP

Error image similar to this one. "CHIP MAIN MEMORY WITH THE CONTENTS ARE IN DISAGREEMENT"
![image](https://user-images.githubusercontent.com/17622363/131957145-87d6c345-1969-4cff-8dde-632df3fb607e.jpeg)

My dumb rom has same size of my previous backup that I get on first patch on osx 11.3, around 8mb (8,388,608 bytes).

**Comment by IsmaelHG** [comment]
You have selected the W25X80 chip on the programmer software (which is only 1MByte vs 8MByte of the macbook ROM). Did you use the Auto option? I don't recommend using it, instead do it manually:

1- Take a look at the motherboard and check the BIOS chip manufacturer and model. Select the proper chip (SPI,MXIC,MX25L6405D in my case and also probably yours). 

![Captura de pantalla 2021-09-03 090104](https://user-images.githubusercontent.com/40826314/131964205-099cafd2-b4a7-47b2-a4bf-0a8199fb90df.png)

2- Connect the SOP8 clip and make sure all 8 pins are touching the chip.

3- Click the Erase button on the software (only takes a few seconds)

4- Click on Blank to check if the chip is empty (it should be)

5- Now open the dump rom and click Write (will take a few minutes)

6- Open the dump again and click Verify. Do this 6th step twice to make sure the BIOS is correctly flashed

I'm using the 1.18 version but it should work on 1.29/1.30

**Comment by imloualvaro** [comment]
@IsmaelHG that was a image taken from internet. And I didn't know about that was necessary to clean the current rom. I follow your advices and my rMPB works fine once again!! Thanks mate, you're GOAT!
